### ISSUE TITLE
大佬，签名报错 是哪边设置错误吗？

### ISSUE THREAD

**Issue by yuzeng84** [linhui0705/certbot-dns-aliyun#1]
Hook '--manual-auth-hook' for example.com reported error code 1
Hook '--manual-auth-hook' for example.com ran with output:
 Alidns接口调用失败。错误码：SignatureDoesNotMatch

**Comment by linhui0705** [comment]
> Hook '--manual-auth-hook' for example.com reported error code 1
> Hook '--manual-auth-hook' for example.com ran with output:
> Alidns接口调用失败。错误码：SignatureDoesNotMatch

> Hook '--manual-auth-hook' for example.com reported error code 1

在startup.sh脚本内，倒数几行Run Scripts注释处，*.example.com域名要改成你自己在阿里云购买注册的域名

> Alidns接口调用失败。错误码：SignatureDoesNotMatch

SignatureDoesNotMatch，无效的签名，应该是你的AccessKeyId和AccessKeySecret没设置对。（P.S.: 阿里云接口错误码可以在这里查：https://error-center.aliyun.com/）
接口鉴权是调用的前提。调用接口前，需要设置开通接口的访问请求权限：
1. 打开阿里云控制台，鼠标指向右上角，点击“访问控制”，创建用户，访问方式选择“编程访问”。
2. 打开刚才新增的用户，创建AccessKey。系统会提供一个文件，只能下载一次，内含AccessKeyId和AccessKeySecret，稍后用于加密请求参数生成签名。
3. 打开权限管理→权限策略管理→创建策略权限，对需要调用的接口配置策略。策略内容如下：
```
{
    "Version": "1",
    "Statement": [
        {
            "Action": "alidns:DescribeSubDomainRecords",
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": "alidns:AddDomainRecord",
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": "alidns:UpdateDomainRecord",
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": "alidns:SetDomainRecordStatus",
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```
4. 对刚才新增的用户和策略权限关联，给用户授权。

感谢你的关注。
